version: '3'
services:
    mt5:
        build:
            context: ./docker/mt5
            dockerfile: Dockerfile
            args:
                APP_ENV: '${APP_ENV}'
                HOST_GID: '${HOST_MT5_UID:-1001}'
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${MT5_DOMAIN}'
            VIRTUAL_HTTP_PORT: '${MT5_HTTP_PORT:-8000}'
            HOST_MT5_UID: '${HOST_MT5_UID:-1001}'
            APP_ENV: '${APP_ENV}'
            APP_SCHEDULE: '${APP_SCHEDULE:-false}'
            VNC_USER: ${VNC_USER:-root}
            VNC_PW: ${VNC_PW:-password}            
        volumes:
            - ./docker/mt5/data-src/.wine/drive_c/Program Files/MetaTrader 5/:/home/kasm-user/.wine/drive_c/Program Files/MetaTrader 5
            - ./docker/mt5/data-src/Desktop/:/home/kasm-user/Desktop
            - './mt5:/home/kasm-user/mt5'
        networks:
            - realjournals
            - nginx-proxy
        depends_on:
            - postgres
            - rabbitmq
            - redis
        ports:
            - "6901:6901"
            - "4901:4901"

    redis:
        build:
            context: ./docker/redis
            dockerfile: Dockerfile
            args:
                REDIS_VERSION: '${REDIS_VERSION:-6}'
        restart: unless-stopped
        volumes:
            - 'realjournals-redis:/data'
        networks:
            - realjournals
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    rabbitmq:
        image: "rabbitmq:3-management"
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'
        networks:
            - realjournals

    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
        networks:
            - realjournals

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${MT5_DOMAIN}'
            VIRTUAL_HTTP_PORT: '${NGINX_HTTP_PORT:-"80"}'
            VIRTUAL_HTTPS_PORT: '${NGINX_HTTPS_PORT:-"443"}'
            MT5_DOMAIN: '${MT5_DOMAIN:-mt5.realjournals.com}'
            NGINX_DEFAULT_MT5_CONFIG: '${NGINX_DEFAULT_MT5_CONFIG}'
        ports:
            - '${NGINX_HTTP_PORT:-80}:${NGINX_HTTP_PORT:-80}'
            - '${NGINX_HTTPS_PORT:-443}:${NGINX_HTTPS_PORT:-443}'
        volumes:
            - '.:/var/www/html'
            - '${HOME}/www/certbot:/var/www/certbot'
            - '${HOME}/lib/letsencrypt:/var/lib/letsencrypt'
            - '${HOME}/letsencrypt:/etc/letsencrypt'
        networks:
            - nginx-proxy
        depends_on:
            - mt5
        healthcheck:
            test: ["CMD-SHELL", "service nginx status || exit 1"]

networks:
    nginx-proxy:
        external: true
    realjournals:
        driver: bridge
volumes:
    realjournals-redis:
        driver: local
